/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package realteller;

import java.util.Scanner;

public class App {
   

    public static void main(String[] args) {
        Bank bank = new Bank();
        Account checkings = new Account("2342", "checkings", 340395);
        Account savings = new Account("2324", "savings", 23242);
        bank.openNewAccount(checkings.getAccountNumber(), checkings);
        bank.openNewAccount(savings.getAccountNumber(), savings);
        System.out.println("Welcome to the bank!");
        System.out.println("Please enter your account number to begin: ");
        Scanner input = new Scanner(System.in);
        String userInput = input.nextLine();
        
        boolean notDone = true;
        do{
            System.out.println("Now accessing bank account number: " + userInput);
            System.out.println("Please enter a number for what you would like to do: ");
            System.out.println("1. Make a deposit");
            System.out.println("2. Make a withdrawal");
            System.out.println("3. Check the balance of the account");
            System.out.println("4. Close the account");
            System.out.println("5. Exit the application");
            int userChoice = input.nextInt();

            if(userChoice > 5 || userChoice < 1){
                System.out.println("Please try again");
            } else if(userChoice == 1){
                System.out.println("How much would you like to deposit?");
                float userAmount = input.nextFloat();
                bank.getAccount(userInput).depositToAccount(userAmount);
                System.out.println("Your new balance is: "+bank.getAccount(userInput).getAccountBalance());
            } else if(userChoice == 2){
                System.out.println("How much would you like to withdrawal? You currently have: "+bank.getAccount(userInput).getAccountBalance());
                float userAmount = input.nextFloat();
                bank.getAccount(userInput).withdrawFromAccount(userAmount);
                System.out.println("Your new balance is: "+bank.getAccount(userInput).getAccountBalance());
            } else if(userChoice == 3){
                System.out.println("Your current balance is: " + bank.getAccount(userInput).checkAccountBalance());
            } else if(userChoice == 4){
                System.out.println("Now closing account T~T");
                bank.closeAccount(userInput);
                System.out.println("Your account is now closed, no going back now...");
            } else if (userChoice == 5){
                System.out.println("Now exiting the ATM, goodbye!");
                notDone = false;
            }

        }while (notDone);

        input.close();
    }
    }

